---
version: '0.1'
services:
  traefik:
    image: library/traefik
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      lan: {}
      backend: